import pox.openflow.libopenflow_01 as of
from pox.core import core
from pox.lib.packet.ethernet import ethernet
from pox.lib.packet.arp import arp
from pox.lib.addresses import IPAddr, EthAddr
from pox.lib.util import dpidToStr
import numpy as np
import networkx as nx

class Routing():

	def __init__(self):
		core.openflow.addListeners(self)
		self.host_location = {}
		self.host_ip_mac = {}
		self.max_hosts = 5

	def _handle_ConnectionUp(self, event):
		self.hostDiscovery(event.connection)

	def hostDiscovery(self, connection):
		for h in range(self.max_hosts):
			arp_req = arp()
			arp_req.hwsrc = EthAddr("00:00:00:00:11:11")
			arp_req.opcode = arp.REQUEST
			arp_req.protosrc = IPAddr("10.0." + str(h) + ".1")
			arp_req.protodst = IPAddr("10.0." + str(h) + ".100")
			ether = ethernet()
			ether.type = ethernet.ARP_TYPE
			ether.dst = EthAddr.BROADCAST
			ether.src = EthAddr("00:00:00:00:11:11")
			ether.payload = arp_req
			msg = of.ofp_packet_out()
			msg.data = ether.pack()
			msg.actions.append(of.ofp_action_output(port = 1))
			connection.send(msg)

	def _handle_PacketIn(self, event):
		eth_frame = event.parsed
		
		if eth_frame.type == ethernet.ARP_TYPE:
			arp_msg = eth_frame.payload
			print(arp_msg)

			if arp_msg.opcode == arp.REPLY and eth_frame.dst == EthAddr("00:00:00:00:11:11"):
				ip_host = arp_msg.protosrc.toStr()
				mac_host = arp_msg.hwsrc.toStr()
				self.host_location[ip_host] = event.dpid
				self.host_ip_mac[ip_host] = mac_host

			elif arp_msg.opcode == arp.REQUEST: # Request coming from an host generated by a response
				# Generating arp reply
				arp_reply = arp()
				arp_reply.hwsrc = EthAddr("00:00:00:00:11:11")
				arp_reply.hwdst = arp_msg.hwsrc
				arp_reply.opcode = arp.REPLY
				arp_reply.protosrc = arp_msg.protodst
				arp_reply.protodst = arp_msg.protosrc

				# Encapsulation of the arp reply inside an ethernet frame
				new_eth_frame = ethernet()
				new_eth_frame.type = ethernet.ARP_TYPE
				new_eth_frame.src = EthAddr("00:00:00:00:11:11")
				new_eth_frame.dst = eth_frame.src
				new_eth_frame.payload = arp_reply

				# Sending the arp reply
				msg = of.ofp_packet_out()
				msg.data = new_eth_frame.pack()
				msg.actions.append(of.ofp_action_output(port = event.port))
				core.openflow.sendToDPID(event.dpid, msg)
			
		elif eth_frame.type == ethernet.IP_TYPE:
			ip_pkt = eth_frame.payload
			print(ip_pkt)
			ip_src = ip_pkt.srcip
			ip_dst = ip_pkt.dstip
			switch_src = self.host_location[ip_src.toStr()]
			switch_dst = self.host_location[ip_dst.toStr()]

			S = list(core.linkDiscovery.switch_id.keys())[list(core.linkDiscovery.switch_id.values()).index(switch_src)]
			D = list(core.linkDiscovery.switch_id.keys())[list(core.linkDiscovery.switch_id.values()).index(switch_dst)]

			graph = core.linkDiscovery.getGraph()
			path = nx.shortest_path(graph, S, D)
			print(path)
			self.install_path(path, ip_src, ip_dst)
			
			# For optimization we can install the reverse path directly
			#self.install_path(path[::-1], ip_dst, ip_src)

	''' Method to install the flow rules across following the path
		Assuming we have a list ['s1', ..., 's_i', s_j', ...] we must:
		- match the IP packet trough ip_src and ip_dst;
		- install a rule that forward the IP packet (matched) from s_i to s_j
		- when the next hop is the last node into the path, on this node we must forward the packet
		  to the port connected with the host 
	'''
	def install_path(self, path, ip_src, ip_dst):
		
		def get_out_port(sid_a, sid_b):
			for link in core.linkDiscovery.links.values():
				if link.sid1 == sid_a and link.sid2 == sid_b:
					return link.port1
				if link.sid1 == sid_b and link.sid2 == sid_a:
					return link.port2
			return None

		# Installing the flow rules
		for i in range(len(path) - 1):
			sid_curr = path[i]
			sid_next = path[i + 1]
			
			print(f"Processing flow rule for {hex(core.linkDiscovery.switch_id[sid_curr])} -> {hex(core.linkDiscovery.switch_id[sid_next])}")

			out_port = get_out_port(sid_curr, sid_next)
			if out_port is None:
				continue

			dpid = core.linkDiscovery.switch_id[sid_curr]
			conn = core.openflow.getConnection(dpid)
			if conn is None:
				continue

			fm = of.ofp_flow_mod()
			fm.priority = 100

			fm.match.dl_type = ethernet.IP_TYPE
			fm.match.nw_src = IPAddr(ip_src)
			fm.match.nw_dst = IPAddr(ip_dst)

			fm.idle_timeout = 500
			fm.hard_timeout = 1000

			fm.actions.append(of.ofp_action_output(port=out_port))
			conn.send(fm)

		# Last hop into the path
		last_sid = path[-1]
		dpid_last = core.linkDiscovery.switch_id[last_sid]
		conn_last = core.openflow.getConnection(dpid_last)

		print(f"Processing output rule for {hex(dpid_last)}\t{conn_last}")

		if conn_last is not None:
			fm = of.ofp_flow_mod()
			fm.priority = 100
			fm.idle_timeout = 500
			fm.hard_timeout = 1000
			fm.match.dl_type = ethernet.IP_TYPE
			fm.match.nw_src = IPAddr(ip_src)
			fm.match.nw_dst = IPAddr(ip_dst)

			# Replacing the destination mac address
			mac_dst = self.host_ip_mac[ip_dst.toStr()]
			fm.actions.append(of.ofp_action_dl_addr.set_dst(EthAddr(mac_dst)))
			fm.actions.append(of.ofp_action_output(port=1))
			conn_last.send(fm)

def launch():
	Routing()
