s1[image]="kathara/sdn"
s1[2]=A
s1[1]=B
s1[0]=E

s2[image]="kathara/sdn"
s2[2]=A
s2[1]=C
s2[0]=F

s3[image]="kathara/sdn"
s3[2]=C
s3[1]=D
s3[0]=G

h1[image]="kathara/base"
h1[0]=E

h2[image]="kathara/base"
h2[0]=F

h3[image]="kathara/base"
h3[0]=G

s1[3]=M
s2[3]=M
s3[3]=M

controller[image]="kathara/pox"
controller[0]=M
controller[bridged]="True"
