# SDN Network
h1[0]=A
s1[0]=A

s1[1]=B
s2[1]=B

s2[0]=E
h2[0]=E

# Management network (c = controller)
s1[2]=G
s2[2]=G
c[0]=G

# Images
h1[image]="kathara/base"
h2[image]="kathara/base"
s1[image]="kathara/sdn"
s2[image]="kathara/sdn"
c[image]="kathara/pox"